# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'txt2pdf2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_widget(object):
    def setupUi(self, main_widget):
        main_widget.setObjectName("main_widget")
        main_widget.resize(600, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_widget.sizePolicy().hasHeightForWidth())
        main_widget.setSizePolicy(sizePolicy)
        main_widget.setMaximumSize(QtCore.QSize(1920, 1080))
        main_widget.setStyleSheet("background-color: rgb(180, 208, 255);\n"
"font: 13pt \"Verdana\";\n"
"\n"
"")
        self.frame = QtWidgets.QFrame(main_widget)
        self.frame.setGeometry(QtCore.QRect(20, 150, 561, 201))
        self.frame.setStyleSheet("border: 3px solid white;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_pdf_path = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_pdf_path.setGeometry(QtCore.QRect(20, 140, 401, 31))
        self.lineEdit_pdf_path.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"font: 13pt \"Verdana\";")
        self.lineEdit_pdf_path.setObjectName("lineEdit_pdf_path")
        self.label_txt_file = QtWidgets.QLabel(self.frame)
        self.label_txt_file.setGeometry(QtCore.QRect(20, 30, 121, 16))
        self.label_txt_file.setStyleSheet("font: 13pt \"Verdana\";\n"
"font-weight: bold;\n"
"border: none")
        self.label_txt_file.setObjectName("label_txt_file")
        self.lineEdit_txt_path = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_txt_path.setGeometry(QtCore.QRect(20, 50, 401, 31))
        self.lineEdit_txt_path.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"font: 13pt \"Verdana\";")
        self.lineEdit_txt_path.setObjectName("lineEdit_txt_path")
        self.pushButton_pdf_path = QtWidgets.QPushButton(self.frame)
        self.pushButton_pdf_path.setGeometry(QtCore.QRect(440, 140, 101, 31))
        self.pushButton_pdf_path.setStyleSheet("QPushButton {\n"
"                                    background-color: rgb(115, 124, 255);\n"
"                                    border-width: 1px;\n"
"                                    border-radius: 15px;\n"
"                                    font: 75 13pt \"Verdana\";\n"
"                                    border: none;\n"
"                                        }\n"
"                    QPushButton:hover {\n"
"                                    background-color: rgb(104, 111, 231);\n"
"                                    }\n"
"                    QPushButton:pressed {\n"
"                                    color: white;\n"
"                                    background-color: rgb(79, 82, 177);}\n"
"")
        self.pushButton_pdf_path.setObjectName("pushButton_pdf_path")
        self.pushButton_txt = QtWidgets.QPushButton(self.frame)
        self.pushButton_txt.setGeometry(QtCore.QRect(440, 50, 101, 31))
        self.pushButton_txt.setStyleSheet("QPushButton {\n"
"                                    background-color: rgb(115, 124, 255);\n"
"                                    border-width: 1px;\n"
"                                    border-radius: 15px;\n"
"                                    font: 75 13pt \"Verdana\";\n"
"                                    border: none;\n"
"                                        }\n"
"                    QPushButton:hover {\n"
"                                    background-color: rgb(104, 111, 231);\n"
"                                    }\n"
"                    QPushButton:pressed {\n"
"                                    color: white;\n"
"                                    background-color: rgb(79, 82, 177);}\n"
"")
        self.pushButton_txt.setObjectName("pushButton_txt")
        self.label_pdf_pfile = QtWidgets.QLabel(self.frame)
        self.label_pdf_pfile.setGeometry(QtCore.QRect(20, 120, 101, 16))
        self.label_pdf_pfile.setStyleSheet("font: 75 13pt \"Verdana\";\n"
"font-weight: bold;\n"
"border: none")
        self.label_pdf_pfile.setObjectName("label_pdf_pfile")
        self.group_type = QtWidgets.QGroupBox(main_widget)
        self.group_type.setGeometry(QtCore.QRect(20, 40, 561, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_type.sizePolicy().hasHeightForWidth())
        self.group_type.setSizePolicy(sizePolicy)
        self.group_type.setMaximumSize(QtCore.QSize(1920, 100))
        self.group_type.setSizeIncrement(QtCore.QSize(0, 0))
        self.group_type.setStyleSheet("font: 75 13pt \"Verdana\";\n"
"font-weight: bold;\n"
"border: 3px solid white;\n"
"\n"
"")
        self.group_type.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.group_type.setObjectName("group_type")
        self.radioButton_liq = QtWidgets.QRadioButton(self.group_type)
        self.radioButton_liq.setGeometry(QtCore.QRect(130, 40, 121, 21))
        self.radioButton_liq.setStyleSheet("font: 13pt \"Verdana\";\n"
"border: none;\n"
"")
        self.radioButton_liq.setObjectName("radioButton_liq")
        self.radioButton_vol = QtWidgets.QRadioButton(self.group_type)
        self.radioButton_vol.setGeometry(QtCore.QRect(350, 40, 161, 21))
        self.radioButton_vol.setStyleSheet("font: 13pt \"Verdana\";\n"
"border: none;\n"
"\n"
"")
        self.radioButton_vol.setObjectName("radioButton_vol")
        self.horizontalLayoutWidget = QtWidgets.QWidget(main_widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 370, 561, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_convert = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_convert.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_convert.sizePolicy().hasHeightForWidth())
        self.pushButton_convert.setSizePolicy(sizePolicy)
        self.pushButton_convert.setMinimumSize(QtCore.QSize(150, 40))
        self.pushButton_convert.setMaximumSize(QtCore.QSize(150, 40))
        self.pushButton_convert.setBaseSize(QtCore.QSize(150, 40))
        self.pushButton_convert.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_convert.setStyleSheet("QPushButton {\n"
"                                    background-color: rgb(255, 138, 36);\n"
"                                    border-width: 5px;\n"
"                                    border-radius: 15px;\n"
"                                    font: 75 15pt \"Verdana\";\n"
"                                    border-color: black;\n"
"                                    }\n"
"QPushButton:hover {\n"
"                                    background-color: rgb(232, 127, 32);\n"
"                                border: 1px;\n"
"                                border-color: black; \n"
"                                    }\n"
"QPushButton:pressed {\n"
"                                    color: white;\n"
"                                    background-color: rgb(197, 108, 27);\n"
"                                border-width: 1px;\n"
"                                border-color: white;\n"
"                                }\n"
"QPushButton:disabled {\n"
"                                opacity: 50;\n"
"                                }")
        self.pushButton_convert.setAutoRepeat(False)
        self.pushButton_convert.setObjectName("pushButton_convert")
        self.horizontalLayout.addWidget(self.pushButton_convert)
        self.textBox1 = QtWidgets.QPlainTextEdit(main_widget)
        self.textBox1.setGeometry(QtCore.QRect(20, 470, 561, 271))
        self.textBox1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBox1.setObjectName("textBox1")

        self.retranslateUi(main_widget)
        QtCore.QMetaObject.connectSlotsByName(main_widget)

    def retranslateUi(self, main_widget):
        _translate = QtCore.QCoreApplication.translate
        main_widget.setWindowTitle(_translate("main_widget", "TXT a PDF v1.0"))
        self.lineEdit_pdf_path.setText(_translate("main_widget", "Selecciona una carpeta de destino..."))
        self.label_txt_file.setText(_translate("main_widget", "Archivo de TXT"))
        self.lineEdit_txt_path.setText(_translate("main_widget", "Selecciona un archivo TXT..."))
        self.pushButton_pdf_path.setText(_translate("main_widget", "Guardar en..."))
        self.pushButton_txt.setText(_translate("main_widget", "Seleccionar..."))
        self.label_pdf_pfile.setText(_translate("main_widget", "Archivo PDF"))
        self.group_type.setTitle(_translate("main_widget", "Convertir a PDF..."))
        self.radioButton_liq.setText(_translate("main_widget", "Liquidaciones"))
        self.radioButton_vol.setText(_translate("main_widget", "Volantes de Nomina"))
        self.pushButton_convert.setText(_translate("main_widget", "Convertir"))
