# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'txt2pdf.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(572, 712)
        MainWindow.setMaximumSize(QtCore.QSize(580, 735))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(180, 208, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 120, 561, 181))
        self.frame.setStyleSheet("border: 3px solid white;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_pdf_path = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_pdf_path.setGeometry(QtCore.QRect(20, 110, 401, 31))
        self.lineEdit_pdf_path.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"font: 75 8pt \"Verdana\";")
        self.lineEdit_pdf_path.setObjectName("lineEdit_pdf_path")
        self.label_txt_file = QtWidgets.QLabel(self.frame)
        self.label_txt_file.setGeometry(QtCore.QRect(20, 20, 121, 16))
        self.label_txt_file.setStyleSheet("font: 8pt \"Verdana\";\n"
"font-weight: bold;\n"
"border: none")
        self.label_txt_file.setObjectName("label_txt_file")
        self.lineEdit_txt_path = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_txt_path.setGeometry(QtCore.QRect(20, 40, 401, 31))
        self.lineEdit_txt_path.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"font: 75 8pt \"Verdana\";")
        self.lineEdit_txt_path.setObjectName("lineEdit_txt_path")
        self.pushButton_pdf_path = QtWidgets.QPushButton(self.frame)
        self.pushButton_pdf_path.setGeometry(QtCore.QRect(440, 110, 101, 31))
        self.pushButton_pdf_path.setStyleSheet("QPushButton {\n"
"                                    background-color: rgb(115, 124, 255);\n"
"                                    border-width: 1px;\n"
"                                    border-radius: 15px;\n"
"                                    font: 75 8pt \"Verdana\";\n"
"                                    border: none;\n"
"                                        }\n"
"                    QPushButton:hover {\n"
"                                    background-color: rgb(104, 111, 231);\n"
"                                    }\n"
"                    QPushButton:pressed {\n"
"                                    color: white;\n"
"                                    background-color: rgb(79, 82, 177);}\n"
"")
        self.pushButton_pdf_path.setObjectName("pushButton_pdf_path")
        self.pushButton_txt = QtWidgets.QPushButton(self.frame)
        self.pushButton_txt.setGeometry(QtCore.QRect(440, 40, 101, 31))
        self.pushButton_txt.setStyleSheet("QPushButton {\n"
"                                    background-color: rgb(115, 124, 255);\n"
"                                    border-width: 1px;\n"
"                                    border-radius: 15px;\n"
"                                    font: 75 8pt \"Verdana\";\n"
"                                    border: none;\n"
"                                        }\n"
"                    QPushButton:hover {\n"
"                                    background-color: rgb(104, 111, 231);\n"
"                                    }\n"
"                    QPushButton:pressed {\n"
"                                    color: white;\n"
"                                    background-color: rgb(79, 82, 177);}\n"
"")
        self.pushButton_txt.setObjectName("pushButton_txt")
        self.label_pdf_pfile = QtWidgets.QLabel(self.frame)
        self.label_pdf_pfile.setGeometry(QtCore.QRect(20, 90, 101, 16))
        self.label_pdf_pfile.setStyleSheet("font: 75 8pt \"Verdana\";\n"
"font-weight: bold;\n"
"border: none")
        self.label_pdf_pfile.setObjectName("label_pdf_pfile")
        self.textBox1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textBox1.setGeometry(QtCore.QRect(10, 320, 561, 271))
        self.textBox1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Verdana\";")
        self.textBox1.setObjectName("textBox1")
        self.group_type = QtWidgets.QGroupBox(self.centralwidget)
        self.group_type.setGeometry(QtCore.QRect(10, 10, 561, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_type.sizePolicy().hasHeightForWidth())
        self.group_type.setSizePolicy(sizePolicy)
        self.group_type.setMaximumSize(QtCore.QSize(1920, 100))
        self.group_type.setSizeIncrement(QtCore.QSize(0, 0))
        self.group_type.setStyleSheet("font: 75 9pt \"Verdana\";\n"
"font-weight: bold;\n"
"border: 3px solid white;\n"
"\n"
"")
        self.group_type.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.group_type.setObjectName("group_type")
        self.radioButton_liq = QtWidgets.QRadioButton(self.group_type)
        self.radioButton_liq.setGeometry(QtCore.QRect(130, 40, 121, 21))
        self.radioButton_liq.setStyleSheet("font: 75 8pt \"Verdana\";\n"
"border: none;\n"
"")
        self.radioButton_liq.setObjectName("radioButton_liq")
        self.radioButton_vol = QtWidgets.QRadioButton(self.group_type)
        self.radioButton_vol.setGeometry(QtCore.QRect(350, 40, 161, 21))
        self.radioButton_vol.setStyleSheet("font: 75 8pt \"Verdana\";\n"
"border: none;\n"
"\n"
"")
        self.radioButton_vol.setObjectName("radioButton_vol")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 610, 561, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_convert = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_convert.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_convert.sizePolicy().hasHeightForWidth())
        self.pushButton_convert.setSizePolicy(sizePolicy)
        self.pushButton_convert.setMinimumSize(QtCore.QSize(150, 40))
        self.pushButton_convert.setMaximumSize(QtCore.QSize(150, 40))
        self.pushButton_convert.setBaseSize(QtCore.QSize(150, 40))
        self.pushButton_convert.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_convert.setStyleSheet("QPushButton {\n"
"                                    background-color: rgb(255, 138, 36);\n"
"                                    border-width: 5px;\n"
"                                    border-radius: 15px;\n"
"                                    font: 75 12pt \"Verdana\";\n"
"                                    border-color: black;\n"
"                                    }\n"
"QPushButton:hover {\n"
"                                    background-color: rgb(232, 127, 32);\n"
"                                border: 1px;\n"
"                                border-color: black; \n"
"                                    }\n"
"QPushButton:pressed {\n"
"                                    color: white;\n"
"                                    background-color: rgb(197, 108, 27);\n"
"                                border-width: 1px;\n"
"                                border-color: white;\n"
"                                }\n"
"QPushButton:disabled {\n"
"                                opacity: 50;\n"
"                                }")
        self.pushButton_convert.setAutoRepeat(False)
        self.pushButton_convert.setObjectName("pushButton_convert")
        self.horizontalLayout.addWidget(self.pushButton_convert)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 572, 22))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuHerramientas = QtWidgets.QMenu(self.menubar)
        self.menuHerramientas.setObjectName("menuHerramientas")
        MainWindow.setMenuBar(self.menubar)
        self.actionSalir = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/exitIcon/2232198.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSalir.setIcon(icon)
        self.actionSalir.setObjectName("actionSalir")
        self.actionEnviar_por_correo = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/sendMailIcon/475610-200.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionEnviar_por_correo.setIcon(icon1)
        self.actionEnviar_por_correo.setObjectName("actionEnviar_por_correo")
        self.menuArchivo.addAction(self.actionSalir)
        self.menuHerramientas.addAction(self.actionEnviar_por_correo)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuHerramientas.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Convertir TXT a PDF"))
        self.lineEdit_pdf_path.setText(_translate("MainWindow", "Selecciona una carpeta de destino..."))
        self.label_txt_file.setText(_translate("MainWindow", "Archivo de TXT"))
        self.lineEdit_txt_path.setText(_translate("MainWindow", "Selecciona un archivo TXT..."))
        self.pushButton_pdf_path.setText(_translate("MainWindow", "Guardar en..."))
        self.pushButton_txt.setText(_translate("MainWindow", "Seleccionar..."))
        self.label_pdf_pfile.setText(_translate("MainWindow", "Archivo PDF"))
        self.group_type.setTitle(_translate("MainWindow", "Convertir a PDF..."))
        self.radioButton_liq.setText(_translate("MainWindow", "Liquidaciones"))
        self.radioButton_vol.setText(_translate("MainWindow", "Volantes de Nomina"))
        self.pushButton_convert.setText(_translate("MainWindow", "Convertir"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuHerramientas.setTitle(_translate("MainWindow", "Herramientas"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionSalir.setShortcut(_translate("MainWindow", "Meta+Q"))
        self.actionEnviar_por_correo.setText(_translate("MainWindow", "Enviar por correo"))

